# Generated by Django 2.2 on 2019-04-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', 'data_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelstatistic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
