# Generated by Django 2.1.7 on 2019-03-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HotelType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.HotelType'),
        ),
        migrations.RunSQL(
            """
            INSERT INTO 'HotelType' ('id', 'type') 
            VALUES(NULL,3, 'Hotel');
            """)
    ]
