# Generated by Django 2.1.7 on 2019-03-03 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=512)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='street',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='hoteltype',
            name='type',
            field=models.CharField(max_length=1024),
        ),
    ]
